### ISSUE TITLE
Hyperparameter for point culling

### ISSUE THREAD

**Issue by BooguTeam** [graphdeco-inria/reduced-3dgs#15]
Hi, thanks for your great work. I am curious about the default hyperparameters for training.

I simply run the `python train.py -s ~/workspace/datasets/db/playroom/colmap -m ./output/DB/playroom--eval`. The output contains 240W Gaussian primitives, which is higher than the vanilla GS.

**Comment by Harr7y** [comment]
configuration["mercy_points"]  in _full_eval.py_.
