### ISSUE TITLE
Webviewer on Project Page

### ISSUE THREAD

**Issue by Gaozhongpai** [graphdeco-inria/reduced-3dgs#16]
Thanks for releasing the code. Could you provide information on how to build the web viewer as shown on the project page: https://repo-sam.inria.fr/fungraph/reduced_3dgs/webviewer.html ? Thank you very much.

**Comment by alanvinx** [comment]
Hi, here is the web viewer's repo with the instructions to run it https://github.com/alanvinx/3dgs_webviewer/tree/dev.
When cloning this repo please make sure to add `-b dev`.
