### ISSUE TITLE
ERROR: Failed building wheel for diff_gaussian_rasterization

### ISSUE THREAD

**Issue by ljh16042** [graphdeco-inria/reduced-3dgs#2]
I found that there is no glm in diff_gaussian_rasterization/third_party. I cloned it here, but the reinstall still failed.

**Comment by HuskyRye** [comment]
try this:
sudo apt install libglm-dev

**Comment by ljh16042** [comment]
I changed the `/w` line to `-w`, and successfully installed `diff_gaussian_rasterization`. The reason is that `/w` is an MSVC command, and I am installing on an Ubuntu system. It has nothing to do with `glm`.
https://github.com/graphdeco-inria/reduced-3dgs/blob/36f7620e8126d1b0682f80aaf9448d18368d804b/submodules/diff-gaussian-rasterization/setup.py#L34
However, the point cloud file obtained from the training only has tens of thousands or even no points. The rendered image is all black.

**Comment by PanagiotisP** [comment]
I've added glm as a submodule.
Due to some issues I made a last-minute change to not include the submodules `simple-knn` and the rasteriser as git submodules, but I forgot about glm. It should install easily now.

@ljh16042 what about the other issue?
