### ISSUE TITLE
SIBR error

### ISSUE THREAD

**Issue by smart4654154** [graphdeco-inria/reduced-3dgs#5]
This is the result of my training
![image](https://github.com/user-attachments/assets/381ddeb0-42bb-4b86-813a-e03f6a59c4ea)

I use this viewer:
Pre-built Windows Binaries
We provide pre-built binaries for Windows [here](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/binaries/viewers.zip). We recommend using them on Windows for an efficient setup, since the building of SIBR involves several external dependencies that must be downloaded and compiled on-the-fly.

But there was an error, can you help me?
![image](https://github.com/user-attachments/assets/a9d1068b-4bfd-483a-9f91-5a2ed3913948)
thank you

**Comment by PanagiotisP** [comment]
Hm yeah, I'm sorry. I haven't refreshed the pre-build binaries for this project -_-. I'm gonna comment out the relative section until I do. Until then, installing from source is the only way to go.
