### ISSUE TITLE
cannot import name 'rasterize_gaussians_variableSH_bands'

### ISSUE THREAD

**Issue by Richardder** [graphdeco-inria/reduced-3dgs#6]
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/richard/program/reduced-3dgs/gaussian_renderer/__init__.py", line 15, in <module>
    from diff_gaussian_rasterization._C import rasterize_gaussians_variableSH_bands
ImportError: cannot import name 'rasterize_gaussians_variableSH_bands' from 'diff_gaussian_rasterization._C' (/home/richard/miniconda3/envs/gaussian_splatting/lib/python3.7/site-packages/diff_gaussian_rasterization/_C.cpython-37m-x86_64-linux-gnu.so)

I tried to reinstall the 'environment.yml' but the 'submoduled/diff-gaussian-rasterization' could not be installed. 

Building wheels for collected packages: diff-gaussian-rasterization, simple-knn
  Building wheel for diff-gaussian-rasterization (setup.py): started
  Building wheel for diff-gaussian-rasterization (setup.py): finished with status 'error'

  Running setup.py install for diff-gaussian-rasterization: started
  Running setup.py install for diff-gaussian-rasterization: finished with status 'error'

...
l large amount of info
...

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> diff-gaussian-rasterization

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
                                                                                                                                                                                 failed

CondaEnvException: Pip failed

and then i tried the gaussian-splatting, i could install the 'submodules/diff-gaussian-rasterization' there ,and i was confused.

**Comment by PanagiotisP** [comment]
Hi. I might have messed up some things in the `environment.yml` file, after making a last-minute change with the submodule (that I will revert when I get back to office).
For now, can you try running `pip install submodules/diff-gaussian-rasterization/` manually?

**Comment by Richardder** [comment]
> Hi. I might have messed up some things in the `environment.yml` file, after making a last-minute change with the submodule (that I will revert when I get back to office). For now, can you try running `pip install submodules/diff-gaussian-rasterization/` manually?

It still didn't work out.

**Comment by Richardder** [comment]
I followed the closed issue, changed the **/w** line to **-w**, and successfully installed it.

**Comment by PanagiotisP** [comment]
Thanks for getting back to me!
I used this flag during development to pinpoint the compiler errors more easily. I removed it [here](https://github.com/graphdeco-inria/reduced-3dgs/commit/13e7393af8ecd83d69197dec7e4c891b333a7c1c) since it creates problems for non-MSVC users.

**Comment by GoodandNo** [comment]
hello，I met the same error，can u tell me that how to fix it? I run it on the Windows(pycharm),cuda11.7,pytorch=2.0.1-cu117, and i installed diff_gaussian_rasterization-0.0.0 successfully.

R:\anaconda\envs\3d_gaussian_splatting\python.exe R:/3DGS/reduced-3dgs-main/train.py 
Traceback (most recent call last):
  File "R:\3DGS\reduced-3dgs-main\train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "R:\3DGS\reduced-3dgs-main\gaussian_renderer\__init__.py", line 15, in <module>
    from diff_gaussian_rasterization._C import rasterize_gaussians_variableSH_bands
ImportError: cannot import name 'rasterize_gaussians_variableSH_bands' from 'diff_gaussian_rasterization._C' (R:\anaconda\envs\3d_gaussian_splatting\lib\site-packages\diff_gaussian_rasterization\_C.cp310-win_amd64.pyd)

i didn't find the closed issue,so i'm cofused that how to fix the problem,i even don't understand what were you discussing.

**Comment by PanagiotisP** [comment]
Hi!
Can you make sure that `ext.cpp` has exported the function [here](https://github.com/graphdeco-inria/reduced-3dgs/blob/13e7393af8ecd83d69197dec7e4c891b333a7c1c/submodules/diff-gaussian-rasterization/ext.cpp#L17)?
