### ISSUE TITLE
About the PLY file format changes for reduced 3dgs and how it should be implemented in unity

### ISSUE THREAD

**Issue by Songxinlei** [graphdeco-inria/reduced-3dgs#9]
reduced 3dgsCompared to 3dgs, the data format of the PLY file has changed, and the logical implementation has changed in the [Guassian Splatting playgroud in Unity](https://github.com/aras-p/UnityGaussianSplatting). Is there a solution to this?

**Comment by PanagiotisP** [comment]
Hello.
Unfortunately, we do not support this implementation. Probably, you should check with them to incorporate the new ply format to unity

**Comment by Songxinlei** [comment]
Thank you. I guess I should make the code logic changes myself based on the point cloud file format. Thank you for your reply.
